name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
      - .github/workflows
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - 'stable'
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      # first, install libevent
      - run: sudo apt-get update && sudo apt-get install -y libevent-dev vlc

        # then, instal https://github.com/ossrs/srs
        # SRS is a dependency of our RTMP server implementation, and we need to build it from source to get the static libraries
        # we'll use both our own RTMP server and the SRS libraries in our tests, so we need to build SRS as part of our CI setup
      - run: |
          git clone -b develop https://github.com/ossrs/srs.git
          cd srs/trunk
          ./configure
          make
          ./etc/init.d/srs start

      - run: nimble install -Y
      - run: nim c -r src/${{ github.event.repository.name }}.nim
      - run: nimble test
